apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-tomcat-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat-pod
        image: tomcat:latest
        volumeMounts:
        - name: tomcat-pvc
          mountPath: "/opt/var"
  volumeClaimTemplates:
  - metadata:
      name: tomcat-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi