apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsat-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsat-main
  template:
    metadata:
      labels:
        app: jsat-main
        role: jsat-main-tomcat
    spec:
      containers:
      - name: jsat-main
        image: telpin-jsat-main
        imagePullPolicy: Never # Importante para usar registry local
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jsat-main
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    role: jsat-main-tomcat