apiVersion: v1
kind: PersistentVolume
metadata:
  name: jsat-pv
  labels:
    type: local
    app: jsat
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/jsat